export const MY_CONST_OBJECT = {};

export const FORM_VALIDATION_MESSAGES = {
  EN: {
    name: {
      required: "Name is required",
      number: "Name connot contain numbers",
      maxlength: "Name cannot be longer than 50 characters.",
      alphanumeric: "Letters only please",
      lettersonly: "Letters only please",
    },
    number: {
      required: "Account Number is required",
    },
    firstName: {
      required: "First Name is required",
      simplealphabeticlatinarabic: "Letters, And Spaces Only Please",
    },
    lastName: {
      required: "Last Name is required",
      simplealphabeticlatinarabic: "Letters, And Spaces Only Please",
    },
    emailAddress: {
      required: "Email is required",
    },
    EmailAddress: {
      email: "Invalid email address. Please enter again.",
    },
    contactNumber: {
      required: "Contact Number is required",
    },
    companyName: {
      required: "This Field Is Required.",
      simplealphabeticlatinarabic: "Letters, And Spaces Only Please",
    },
    description: {
      required: "Description is required",
    },
    socialAd: {
      required: "Select one option",
    },
    reason: {
      required: "Please write your question",
    },
  },
  AR: {
    name: {
      required: "يرجى كتابة الاسم ",
    },
    number: {
      required: "هذا الحقل إلزامي",
    },
    firstName: {
      required: "هذا الحقل إلزامي",
      simplealphabeticlatinarabic: "الرجاء استخدام الأحرف الأبجدية فقط",
    },
    lastName: {
      required: "هذا الحقل إلزامي",
      simplealphabeticlatinarabic: "الرجاء استخدام الأحرف الأبجدية فقط",
    },
    designation: {
      required: "هذا الحقل إلزامي",
      simplealphabeticlatinarabic: "الرجاء استخدام الأحرف الأبجدية فقط",
    },
    emailAddress: {
      required: "هذا الحقل إلزامي",
      email: "الرجاء إدخال عنوان بريد إلكتروني صحيح",
    },
    EmailAddress: {
      required: "يرجى كتابة البريد الإلكتروني",
    },
    phone1: {
      required: "هذا الحقل إلزامي",
      pattern: "تنسيق الرقم غير صالح",
    },
    companyName: {
      required: "هذا الحقل إلزامي",
      simplealphabeticlatinarabic: "الرجاء استخدام الأحرف الأبجدية فقط",
    },
    description: {
      required: "هذا الحقل إلزامي",
    },
    socialAd: {
      required: "اختر احد الخيارات",
    },
    reason: {
      required: "يرجى كتابة سؤالك",
    },
  },
};

export const DIAL_CODE_DATA = [
  { id: "af", text: "+93" },
  { id: "al", text: "+355" },
  { id: "dz", text: "+213" },
  { id: "as", text: "+1684" },
  { id: "ad", text: "+376" },
  { id: "ao", text: "+244" },
  { id: "ai", text: "+1264" },
  { id: "ag", text: "+1268" },
  { id: "ar", text: "+54" },
  { id: "am", text: "+374" },
  { id: "aw", text: "+297" },
  { id: "au", text: "+61" },
  { id: "at", text: "+43" },
  { id: "az", text: "+994" },
  { id: "bs", text: "+1242" },
  { id: "bh", text: "+973" },
  { id: "bd", text: "+880" },
  { id: "bb", text: "+1246" },
  { id: "by", text: "+375" },
  { id: "be", text: "+32" },
  { id: "bz", text: "+501" },
  { id: "bj", text: "+229" },
  { id: "bm", text: "+1441" },
  { id: "bt", text: "+975" },
  { id: "bo", text: "+591" },
  { id: "ba", text: "+387" },
  { id: "bw", text: "+267" },
  { id: "br", text: "+55" },
  { id: "io", text: "+246" },
  { id: "vg", text: "+1284" },
  { id: "bn", text: "+673" },
  { id: "bg", text: "+359" },
  { id: "bf", text: "+226" },
  { id: "bi", text: "+257" },
  { id: "kh", text: "+855" },
  { id: "cm", text: "+237" },
  { id: "ca", text: "+1" },
  { id: "cv", text: "+238" },
  { id: "bq", text: "+599" },
  { id: "ky", text: "+1345" },
  { id: "cf", text: "+236" },
  { id: "td", text: "+235" },
  { id: "cl", text: "+56" },
  { id: "cn", text: "+86" },
  { id: "cx", text: "+61" },
  { id: "cc", text: "+61" },
  { id: "co", text: "+57" },
  { id: "km", text: "+269" },
  { id: "cd", text: "+243" },
  { id: "cg", text: "+242" },
  { id: "ck", text: "+682" },
  { id: "cr", text: "+506" },
  { id: "ci", text: "+225" },
  { id: "hr", text: "+385" },
  { id: "cu", text: "+53" },
  { id: "cw", text: "+599" },
  { id: "cy", text: "+357" },
  { id: "cz", text: "+420" },
  { id: "dk", text: "+45" },
  { id: "dj", text: "+253" },
  { id: "dm", text: "+1767" },
  { id: "do", text: "+1" },
  { id: "ec", text: "+593" },
  { id: "eg", text: "+20" },
  { id: "sv", text: "+503" },
  { id: "gq", text: "+240" },
  { id: "er", text: "+291" },
  { id: "ee", text: "+372" },
  { id: "et", text: "+251" },
  { id: "fk", text: "+500" },
  { id: "fo", text: "+298" },
  { id: "fj", text: "+679" },
  { id: "fi", text: "+358" },
  { id: "fr", text: "+33" },
  { id: "gf", text: "+594" },
  { id: "pf", text: "+689" },
  { id: "ga", text: "+241" },
  { id: "gm", text: "+220" },
  { id: "ge", text: "+995" },
  { id: "de", text: "+49" },
  { id: "gh", text: "+233" },
  { id: "gi", text: "+350" },
  { id: "gr", text: "+30" },
  { id: "gl", text: "+299" },
  { id: "gd", text: "+1473" },
  { id: "gp", text: "+590" },
  { id: "gu", text: "+1671" },
  { id: "gt", text: "+502" },
  { id: "gg", text: "+44" },
  { id: "gn", text: "+224" },
  { id: "gw", text: "+245" },
  { id: "gy", text: "+592" },
  { id: "ht", text: "+509" },
  { id: "hn", text: "+504" },
  { id: "hk", text: "+852" },
  { id: "hu", text: "+36" },
  { id: "is", text: "+354" },
  { id: "in", text: "+91" },
  { id: "id", text: "+62" },
  { id: "ir", text: "+98" },
  { id: "iq", text: "+964" },
  { id: "ie", text: "+353" },
  { id: "im", text: "+44" },
  { id: "il", text: "+972" },
  { id: "it", text: "+39" },
  { id: "jm", text: "+1" },
  { id: "jp", text: "+81" },
  { id: "je", text: "+44" },
  { id: "jo", text: "+962" },
  { id: "kz", text: "+7" },
  { id: "ke", text: "+254" },
  { id: "ki", text: "+686" },
  { id: "xk", text: "+383" },
  { id: "kw", text: "+965" },
  { id: "kg", text: "+996" },
  { id: "la", text: "+856" },
  { id: "lv", text: "+371" },
  { id: "lb", text: "+961" },
  { id: "ls", text: "+266" },
  { id: "lr", text: "+231" },
  { id: "ly", text: "+218" },
  { id: "li", text: "+423" },
  { id: "lt", text: "+370" },
  { id: "lu", text: "+352" },
  { id: "mo", text: "+853" },
  { id: "mk", text: "+389" },
  { id: "mg", text: "+261" },
  { id: "mw", text: "+265" },
  { id: "my", text: "+60" },
  { id: "mv", text: "+960" },
  { id: "ml", text: "+223" },
  { id: "mt", text: "+356" },
  { id: "mh", text: "+692" },
  { id: "mq", text: "+596" },
  { id: "mr", text: "+222" },
  { id: "mu", text: "+230" },
  { id: "yt", text: "+262" },
  { id: "mx", text: "+52" },
  { id: "fm", text: "+691" },
  { id: "md", text: "+373" },
  { id: "mc", text: "+377" },
  { id: "mn", text: "+976" },
  { id: "me", text: "+382" },
  { id: "ms", text: "+1664" },
  { id: "ma", text: "+212" },
  { id: "mz", text: "+258" },
  { id: "mm", text: "+95" },
  { id: "na", text: "+264" },
  { id: "nr", text: "+674" },
  { id: "np", text: "+977" },
  { id: "nl", text: "+31" },
  { id: "nc", text: "+687" },
  { id: "nz", text: "+64" },
  { id: "ni", text: "+505" },
  { id: "ne", text: "+227" },
  { id: "ng", text: "+234" },
  { id: "nu", text: "+683" },
  { id: "nf", text: "+672" },
  { id: "kp", text: "+850" },
  { id: "mp", text: "+1670" },
  { id: "no", text: "+47" },
  { id: "om", text: "+968" },
  { id: "pk", text: "+92" },
  { id: "pw", text: "+680" },
  { id: "ps", text: "+970" },
  { id: "pa", text: "+507" },
  { id: "pg", text: "+675" },
  { id: "py", text: "+595" },
  { id: "pe", text: "+51" },
  { id: "ph", text: "+63" },
  { id: "pl", text: "+48" },
  { id: "pt", text: "+351" },
  { id: "pr", text: "+1" },
  { id: "qa", text: "+974" },
  { id: "re", text: "+262" },
  { id: "ro", text: "+40" },
  { id: "ru", text: "+7" },
  { id: "rw", text: "+250" },
  { id: "bl", text: "+590" },
  { id: "sh", text: "+290" },
  { id: "kn", text: "+1869" },
  { id: "lc", text: "+1758" },
  { id: "mf", text: "+590" },
  { id: "pm", text: "+508" },
  { id: "vc", text: "+1784" },
  { id: "ws", text: "+685" },
  { id: "sm", text: "+378" },
  { id: "st", text: "+239" },
  { id: "sa", text: "+966" },
  { id: "sn", text: "+221" },
  { id: "rs", text: "+381" },
  { id: "sc", text: "+248" },
  { id: "sl", text: "+232" },
  { id: "sg", text: "+65" },
  { id: "sx", text: "+1721" },
  { id: "sk", text: "+421" },
  { id: "si", text: "+386" },
  { id: "sb", text: "+677" },
  { id: "so", text: "+252" },
  { id: "za", text: "+27" },
  { id: "kr", text: "+82" },
  { id: "ss", text: "+211" },
  { id: "es", text: "+34" },
  { id: "lk", text: "+94" },
  { id: "sd", text: "+249" },
  { id: "sr", text: "+597" },
  { id: "sj", text: "+47" },
  { id: "sz", text: "+268" },
  { id: "se", text: "+46" },
  { id: "ch", text: "+41" },
  { id: "sy", text: "+963" },
  { id: "tw", text: "+886" },
  { id: "tj", text: "+992" },
  { id: "tz", text: "+255" },
  { id: "th", text: "+66" },
  { id: "tl", text: "+670" },
  { id: "tg", text: "+228" },
  { id: "tk", text: "+690" },
  { id: "to", text: "+676" },
  { id: "tt", text: "+1868" },
  { id: "tn", text: "+216" },
  { id: "tr", text: "+90" },
  { id: "tm", text: "+993" },
  { id: "tc", text: "+1649" },
  { id: "tv", text: "+688" },
  { id: "vi", text: "+1340" },
  { id: "ug", text: "+256" },
  { id: "ua", text: "+380" },
  { id: "ae", text: "+971" },
  { id: "gb", text: "+44" },
  { id: "us", text: "+1" },
  { id: "uy", text: "+598" },
  { id: "uz", text: "+998" },
  { id: "vu", text: "+678" },
  { id: "va", text: "+39" },
  { id: "ve", text: "+58" },
  { id: "vn", text: "+84" },
  { id: "wf", text: "+681" },
  { id: "eh", text: "+212" },
  { id: "ye", text: "+967" },
  { id: "zm", text: "+260" },
  { id: "zw", text: "+263" },
  { id: "ax", text: "+358" },
];
